kind: pipeline
type: docker
name: default

steps:
    - name: test
      image: golang:1.13
      commands:
          - sh install_dev_deps.sh
          - go test ./...
          - go build
      depends_on: [ clone ]

    - name: lint
      image: electron2302/golangci-lint-with-gtk3
      commands:
          - go build
          - golangci-lint run -v
      depends_on: [ clone ]
