kind: pipeline
type: docker
name: default

steps:
    - name: test
      image: golang:1.13
      commands:
          - sh install_dev_deps.sh
          - go test ./...
          - go build
      depends_on: [ clone ]

    - name: lint
      image: golangci/golangci-lint
      commands:
          - sh install_dev_deps.sh
          - go build
          - golangci-lint run
      depends_on: [ clone ]
