linters:
    enable-all: true

issues:
    exclude-rules:
        - path: _test\.go
          # Excluded linters from running on tests files.
          linters:
              - dupl
              - funlen
