on: [push, pull_request]
name: GO_Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install development dependencies
      run: |
          sudo sh install_dev_deps.sh
    - name: Go Build
      run: |
          go build
    - name: Run Test
      run: |
          go test -v -coverprofile cover.out ./...
          go tool cover -func cover.out
    - name: Install Golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
    - name: Run Golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ob-algdatii-20ss/leistungsnachweis-teammaze/maze
        tag_with_ref: true
