on: [push, pull_request]
name: GO_Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
          go test -v -coverprofile cover.out ./...
          go tool cover -func cover.out
    - name: Lint
      uses: actions-contrib/golangci-lint@v1
      env:
        GOROOT: ""
      with:
        args: "run"
